# Generated by Django 6.0.4 on 2026-04-27 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('book', 'Book'), ('course', 'Course'), ('skill', 'Skill'), ('video', 'Video')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('weight', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('learning_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spinner.learninglist')),
            ],
        ),
        migrations.CreateModel(
            name='SpinResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('in_progress', 'In_Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='in_progress', max_length=20)),
                ('skip_reason', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spinner.learningitem')),
            ],
        ),
    ]
